import { colors } from './theme';

// Category system — each has a colour + icon used for pins, chips and detail.
export const CATEGORIES = {
  food:    { key: 'food',    label: 'Food',    color: colors.red,   icon: 'restaurant' },
  cafe:    { key: 'cafe',    label: 'Cafes',   color: '#E5A020',    icon: 'cafe' },
  bar:     { key: 'bar',     label: 'Bars',    color: '#7A3FB0',    icon: 'wine' },
  beach:   { key: 'beach',   label: 'Beaches', color: '#1F9BC4',    icon: 'sunny' },
  view:    { key: 'view',    label: 'Views',   color: '#2E7DD8',    icon: 'telescope' },
  park:    { key: 'park',    label: 'Parks',   color: '#2E9E6B',    icon: 'leaf' },
  culture: { key: 'culture', label: 'Culture', color: '#C06A2E',    icon: 'business' },
};

export const CATEGORY_LIST = Object.values(CATEGORIES);

// Real Visakhapatnam places, seeded from local knowledge.
// Coordinates are approximate (good enough for the city map) — verify names,
// areas and anything that reads off before launch. Scores are Adda ranked
// scores (out of 10) seeded for the demo; real ones come from users.
export const SPOTS = [
  // ---- beaches ----
  {
    id: 'rk-beach',
    name: 'RK Beach',
    category: 'beach',
    lat: 17.7108, lng: 83.3247,
    score: 9.2, price: 'Free',
    area: 'Beach Road',
    blurb: 'The heart of the city by the sea. Morning walks, evening chaat carts, and the best people watching in Vizag.',
    friend: { name: 'Priya', tint: '#C0202E', quote: 'Sunset here never gets old' },
  },
  {
    id: 'rushikonda',
    name: 'Rushikonda Beach',
    category: 'beach',
    lat: 17.7826, lng: 83.3852,
    score: 8.8, price: 'Free',
    area: 'Rushikonda',
    blurb: 'Golden sand and the cleanest water near the city. Surf lessons in the morning, quiet evenings.',
    friend: { name: 'Karthik', tint: '#1F9BC4', quote: 'Go early, less crowd' },
  },
  {
    id: 'yarada-beach',
    name: 'Yarada Beach',
    category: 'beach',
    lat: 17.6560, lng: 83.2690,
    score: 8.6, price: 'Free',
    area: 'Yarada',
    blurb: 'Hidden behind the Dolphin\'s Nose hills — a quiet horseshoe of sand that feels a world away from the city.',
  },
  {
    id: 'bheemili',
    name: 'Bheemili Beach',
    category: 'beach',
    lat: 17.8899, lng: 83.4519,
    score: 8.2, price: 'Free',
    area: 'Bheemunipatnam',
    blurb: 'Old Dutch town where the river meets the sea. Quiet, historic, and worth the drive up the coast.',
  },
  {
    id: 'sagar-nagar',
    name: 'Sagar Nagar Beach',
    category: 'beach',
    lat: 17.7570, lng: 83.3560,
    score: 8.0, price: 'Free',
    area: 'Sagar Nagar',
    blurb: 'The locals\' stretch between RK and Rushikonda. Fewer crowds, cleaner sand, great morning runs.',
  },
  {
    id: 'lawsons-bay',
    name: "Lawson's Bay Beach",
    category: 'beach',
    lat: 17.7330, lng: 83.3450,
    score: 8.1, price: 'Free',
    area: 'Lawson\'s Bay Colony',
    blurb: 'Calm waters below Kailasagiri, popular with swimmers at dawn before the city wakes up.',
  },
  {
    id: 'mangamaripeta',
    name: 'Mangamaripeta Beach',
    category: 'beach',
    lat: 17.8080, lng: 83.4050,
    score: 7.9, price: 'Free',
    area: 'Mangamaripeta',
    blurb: 'Fishing village beach past Rushikonda with rock pools at low tide. Carry your own snacks.',
  },
  {
    id: 'gangavaram',
    name: 'Gangavaram Beach',
    category: 'beach',
    lat: 17.6210, lng: 83.2310,
    score: 7.6, price: 'Free',
    area: 'Gangavaram',
    blurb: 'Long, wild and windswept, framed by the port cranes. Filmy sunsets, literally — crews shoot here.',
  },

  // ---- views ----
  {
    id: 'kailasagiri',
    name: 'Kailasagiri',
    category: 'view',
    lat: 17.7496, lng: 83.3437,
    score: 8.9, price: '₹',
    area: 'Hilltop',
    blurb: 'Hilltop park with a ropeway and the widest view of the coastline. Go up for sunset, stay for the breeze.',
    friend: { name: 'Arjun', tint: '#2E7DD8', quote: 'Take the ropeway, worth it' },
  },
  {
    id: 'dolphins-nose',
    name: "Dolphin's Nose",
    category: 'view',
    photoKw: 'lighthouse,cliff',
    lat: 17.6868, lng: 83.2820,
    score: 8.1, price: 'Free',
    area: 'Yarada',
    blurb: 'Dramatic headland shaped like a dolphin. The lighthouse view over the harbour is unreal at dusk.',
  },
  {
    id: 'erra-matti-dibbalu',
    name: 'Erra Matti Dibbalu',
    category: 'view',
    photoKw: 'red,canyon',
    lat: 17.8620, lng: 83.4370,
    score: 8.3, price: 'Free',
    area: 'Bheemili Road',
    blurb: 'Million-year-old red sand ravines glowing at golden hour. One of the most photographed spots on the coast.',
    friend: { name: 'Sana', tint: '#8A57C0', quote: 'Golden hour, thank me later' },
  },
  {
    id: 'ross-hill',
    name: 'Ross Hill Church',
    category: 'view',
    lat: 17.6950, lng: 83.2870,
    score: 7.8, price: 'Free',
    area: 'Old Town',
    blurb: 'Church on a hill over the harbour — one of the few places you can see the whole port spread below.',
  },
  {
    id: 'rushikonda-hill',
    name: 'Rushikonda Hilltop',
    category: 'view',
    lat: 17.7900, lng: 83.3800,
    score: 7.9, price: 'Free',
    area: 'Rushikonda',
    blurb: 'The climb above the beach. Watch the surfers from up top with the whole bay curving away north.',
  },

  // ---- parks ----
  {
    id: 'tenneti-park',
    name: 'Tenneti Park',
    category: 'park',
    lat: 17.7315, lng: 83.3396,
    score: 8.4, price: 'Free',
    area: 'Beach Road',
    blurb: 'Cliffside green with the waves crashing right below. Cleanest sunset seat on the whole stretch.',
  },
  {
    id: 'vuda-park',
    name: 'VUDA Park',
    category: 'park',
    lat: 17.7190, lng: 83.3350,
    score: 7.8, price: '₹',
    area: 'Beach Road',
    blurb: 'The classic city park by the sea — boating pond, big lawns, and evening walkers doing their rounds.',
  },
  {
    id: 'zoo-park',
    name: 'Indira Gandhi Zoological Park',
    category: 'park',
    photoKw: 'zoo,forest',
    lat: 17.7679, lng: 83.3459,
    score: 8.2, price: '₹',
    area: 'Yendada',
    blurb: 'One of the biggest zoos in the country, set inside actual forest. The big cat enclosures are the draw.',
  },
  {
    id: 'kambalakonda',
    name: 'Kambalakonda Eco Park',
    category: 'park',
    photoKw: 'forest,trail',
    lat: 17.7550, lng: 83.3140,
    score: 8.0, price: '₹',
    area: 'Yendada',
    blurb: 'Wildlife sanctuary with proper trekking trails minutes from the city. Go early, carry water.',
    friend: { name: 'Ravi', tint: '#3B7DD8', quote: 'Best morning trek in town' },
  },
  {
    id: 'central-park',
    name: 'VMRDA Central Park',
    category: 'park',
    lat: 17.7290, lng: 83.3110,
    score: 7.6, price: 'Free',
    area: 'Siripuram',
    blurb: 'The city\'s green lung — running track, open gym, and the flag post you can see from everywhere.',
  },

  // ---- culture ----
  {
    id: 'submarine-museum',
    name: 'INS Kursura Submarine Museum',
    category: 'culture',
    photoKw: 'submarine,navy',
    lat: 17.7169, lng: 83.3230,
    score: 8.0, price: '₹',
    area: 'Beach Road',
    blurb: 'A real decommissioned submarine you can walk through. Weirdly moving, especially for kids.',
  },
  {
    id: 'aircraft-museum',
    name: 'TU-142 Aircraft Museum',
    category: 'culture',
    photoKw: 'aircraft,museum',
    lat: 17.7185, lng: 83.3240,
    score: 7.9, price: '₹',
    area: 'Beach Road',
    blurb: 'A giant naval bomber parked across from the sea, turned into a walk-through museum. Pure Beach Road.',
  },
  {
    id: 'simhachalam',
    name: 'Simhachalam Temple',
    category: 'culture',
    photoKw: 'temple,india',
    lat: 17.7666, lng: 83.2503,
    score: 8.7, price: 'Free',
    area: 'Simhachalam',
    blurb: 'The thousand-year-old Varaha Lakshmi Narasimha temple on the hill. The carvings alone are worth the queue.',
    friend: { name: 'Meghana', tint: '#B3474E', quote: 'Go at dawn, it\'s serene' },
  },
  {
    id: 'thotlakonda',
    name: 'Thotlakonda Buddhist Complex',
    category: 'culture',
    photoKw: 'buddhist,ruins',
    lat: 17.8213, lng: 83.4166,
    score: 8.1, price: '₹',
    area: 'Bheemili Road',
    blurb: '2,000-year-old monastery ruins on a hill over the sea. History with the best backdrop in the city.',
  },
  {
    id: 'bavikonda',
    name: 'Bavikonda Monastery',
    category: 'culture',
    photoKw: 'buddhist,stupa',
    lat: 17.7893, lng: 83.3810,
    score: 7.7, price: '₹',
    area: 'Bheemili Road',
    blurb: 'Thotlakonda\'s quieter twin — Buddhist relic mounds and almost nobody around on weekdays.',
  },
  {
    id: 'visakha-museum',
    name: 'Visakha Museum',
    category: 'culture',
    lat: 17.7120, lng: 83.3180,
    score: 7.4, price: '₹',
    area: 'Dutch Bungalow, Beach Road',
    blurb: 'The city\'s story — shipwrecks, the 1971 war, old Vizag photographs — inside a rebuilt Dutch bungalow.',
  },
  {
    id: 'kanaka-mahalakshmi',
    name: 'Kanaka Maha Lakshmi Temple',
    category: 'culture',
    photoKw: 'temple,lamps',
    lat: 17.7050, lng: 83.2950,
    score: 8.0, price: 'Free',
    area: 'Burujupeta',
    blurb: 'The city\'s own goddess, worshipped in the open without a traditional tower. Thursdays get intense.',
  },
  {
    id: 'old-town',
    name: 'Old Town Heritage Walk',
    category: 'culture',
    photoKw: 'heritage,street',
    lat: 17.6990, lng: 83.2920,
    score: 7.6, price: 'Free',
    area: 'One Town',
    blurb: 'Colonial-era streets, the old clock tower, and the harbour lanes where Vizag actually began.',
  },

  // ---- food ----
  {
    id: 'dharani-daspalla',
    name: 'Dharani – Daspalla',
    category: 'food',
    lat: 17.7205, lng: 83.3018,
    score: 8.6, price: '₹₹',
    area: 'Suryabagh',
    blurb: 'Old-school Andhra thali done right. Come hungry, leave defeated. The gongura is the move.',
    friend: { name: 'Meghana', tint: '#B3474E', quote: 'Andhra thali, come hungry' },
  },
  {
    id: 'raju-gari-dhaba',
    name: 'Raju Gari Dhaba',
    category: 'food',
    lat: 17.8180, lng: 83.3480,
    score: 8.7, price: '₹₹',
    area: 'Madhurawada',
    blurb: 'The highway dhaba that became an institution. Ulavacharu, ragi sangati, and country chicken done properly.',
    friend: { name: 'Dev', tint: '#7A3FB0', quote: 'Ulavacharu biryani. That\'s it.' },
  },
  {
    id: 'venkatadri-vantillu',
    name: 'Venkatadri Vantillu',
    category: 'food',
    lat: 17.7420, lng: 83.3370,
    score: 8.5, price: '₹₹',
    area: 'MVP Colony',
    blurb: 'Pure Andhra home-style cooking scaled up. The banana-leaf spread on weekends draws half the city.',
  },
  {
    id: 'sairam-parlour',
    name: 'Sairam Parlour',
    category: 'food',
    lat: 17.7280, lng: 83.3050,
    score: 8.8, price: '₹',
    area: 'Dwaraka Nagar',
    blurb: 'The legendary tiffin stop. Mysore bajji and ghee pesarattu that people plan mornings around.',
    friend: { name: 'Priya', tint: '#C0202E', quote: 'Mysore bajji before 9am' },
  },
  {
    id: 'sea-inn',
    name: 'Sea Inn',
    category: 'food',
    photoKw: 'seafood,grill',
    lat: 17.7800, lng: 83.3830,
    score: 8.4, price: '₹₹',
    area: 'Rushikonda',
    blurb: 'No-frills seafood shack near the beach. Fish straight off the boats, fried while you find a table.',
  },
  {
    id: 'spicy-venue',
    name: 'The Spicy Venue',
    category: 'food',
    lat: 17.7260, lng: 83.3170,
    score: 8.2, price: '₹₹₹',
    area: 'Waltair Uplands',
    blurb: 'Where you take out-of-towners to show off Andhra food with tablecloths. The natu kodi pulusu delivers.',
  },
  {
    id: 'absolute-barbecues',
    name: 'AB\'s – Absolute Barbecues',
    category: 'food',
    lat: 17.7230, lng: 83.3200,
    score: 8.1, price: '₹₹₹',
    area: 'Siripuram',
    blurb: 'The grill-on-the-table buffet for group nights. Book ahead on weekends, always.',
  },
  {
    id: 'mehfil',
    name: 'Mehfil',
    category: 'food',
    lat: 17.7290, lng: 83.3070,
    score: 8.0, price: '₹₹',
    area: 'Dwaraka Nagar',
    blurb: 'Late-night biryani that settles arguments. The family packs feed more people than they claim.',
  },
  {
    id: 'kunda-biryani',
    name: 'Naidu Gari Kunda Biryani',
    category: 'food',
    lat: 17.8050, lng: 83.3600,
    score: 8.3, price: '₹₹',
    area: 'Madhurawada',
    blurb: 'Biryani slow-cooked in clay pots, sealed till your table opens it. Worth the drive and the wait.',
  },
  {
    id: 'jagadamba-chaat',
    name: 'Jagadamba Junction Chaat',
    category: 'food',
    photoKw: 'streetfood,chaat',
    lat: 17.7090, lng: 83.3000,
    score: 8.2, price: '₹',
    area: 'Jagadamba',
    blurb: 'The chaat corners around the junction after a movie — pani puri benchmarks are set here.',
  },
  {
    id: 'beach-road-carts',
    name: 'Beach Road Food Carts',
    category: 'food',
    photoKw: 'streetfood,night',
    lat: 17.7130, lng: 83.3255,
    score: 8.5, price: '₹',
    area: 'Beach Road',
    blurb: 'Muri mixture, punugulu and roasted corn with the sea wind in your face. The city\'s real dining room.',
    friend: { name: 'Aisha', tint: '#E5A020', quote: 'Punugulu + sunset = therapy' },
  },
  {
    id: 'new-andhra-hotel',
    name: 'New Andhra Hotel',
    category: 'food',
    lat: 17.7040, lng: 83.2980,
    score: 7.9, price: '₹',
    area: 'Old Town',
    blurb: 'Old Town meals joint that hasn\'t changed in decades — and shouldn\'t. Fish pulusu on a banana leaf.',
  },
  {
    id: 'kamat',
    name: 'Hotel Kamat',
    category: 'food',
    lat: 17.7250, lng: 83.3120,
    score: 7.7, price: '₹',
    area: 'Asilmetta',
    blurb: 'Dependable South Indian breakfast at all hours. The benne dosa is the quiet star.',
  },
  {
    id: 'flying-spaghetti',
    name: 'Flying Spaghetti Monster',
    category: 'food',
    photoKw: 'pasta,restaurant',
    lat: 17.7235, lng: 83.3210,
    score: 7.8, price: '₹₹₹',
    area: 'Siripuram',
    blurb: 'When the group wants pasta and pizza instead of pulusu. Reliable continental in the middle of town.',
  },

  // ---- cafes ----
  {
    id: 'baes-coffee',
    name: 'Bae\'s Coffee',
    category: 'cafe',
    lat: 17.7400, lng: 83.3350,
    score: 8.6, price: '₹₹',
    area: 'MVP Colony',
    blurb: 'Vizag\'s own specialty coffee chain. Bright rooms, serious brews, and always someone you know.',
    friend: { name: 'Aisha', tint: '#E5A020', quote: 'Best filter coffee in town' },
  },
  {
    id: 'pcc',
    name: 'Pastry, Coffee n Conversation',
    category: 'cafe',
    lat: 17.7280, lng: 83.3230,
    score: 8.4, price: '₹₹',
    area: 'Waltair Uplands',
    blurb: 'The dessert case that started Vizag\'s cafe culture. Red velvet and long conversations.',
  },
  {
    id: 'araku-coffee',
    name: 'Araku Valley Coffee',
    category: 'cafe',
    lat: 17.7215, lng: 83.3175,
    score: 8.5, price: '₹₹',
    area: 'Siripuram',
    blurb: 'Single-origin beans from the valley up the ghats, roasted fresh. The cold brew is dangerously good.',
  },
  {
    id: 'makobrew',
    name: 'Makobrew World Coffee',
    category: 'cafe',
    lat: 17.7850, lng: 83.3700,
    score: 8.1, price: '₹₹',
    area: 'Rushikonda',
    blurb: 'Big glasshouse cafe on the way to the beach. Laptop-friendly by day, buzzing by evening.',
  },
  {
    id: 'coffee-cup',
    name: 'The Coffee Cup',
    category: 'cafe',
    lat: 17.7380, lng: 83.3330,
    score: 7.9, price: '₹₹',
    area: 'MVP Colony',
    blurb: 'The late-night study-and-shisha standby. Reliable cold coffee, easy hours, zero pressure to leave.',
  },
  {
    id: 'cream-stone',
    name: 'Cream Stone',
    category: 'cafe',
    photoKw: 'icecream,dessert',
    lat: 17.7240, lng: 83.3195,
    score: 8.0, price: '₹₹',
    area: 'Siripuram',
    blurb: 'Ice cream folded on the cold stone while you watch. The post-Beach-Road ritual for half the city.',
  },

  // ---- bars ----
  {
    id: 'skyy-bar',
    name: 'SKYY Bar – Novotel',
    category: 'bar',
    photoKw: 'rooftop,bar',
    lat: 17.7118, lng: 83.3222,
    score: 8.5, price: '₹₹₹',
    area: 'Beach Road',
    blurb: 'Rooftop over the bay with the best cocktail view in the city. Book a rail-side table for sunset.',
    friend: { name: 'Dev', tint: '#7A3FB0', quote: 'Rooftop cocktails, harbour view' },
  },
  {
    id: 'tds',
    name: 'Ten Downing Street',
    category: 'bar',
    photoKw: 'pub,night',
    lat: 17.7290, lng: 83.3080,
    score: 8.0, price: '₹₹₹',
    area: 'Dwaraka Nagar',
    blurb: 'The classic British-style pub that\'s hosted every Vizag celebration since forever. Loud, warm, reliable.',
  },
  {
    id: 'vibe-gateway',
    name: 'Vibe – The Gateway',
    category: 'bar',
    photoKw: 'lounge,cocktail',
    lat: 17.7167, lng: 83.3286,
    score: 7.8, price: '₹₹₹',
    area: 'Beach Road',
    blurb: 'Hotel lounge that turns into the weekend spot. Easy access to a midnight beach walk after.',
  },
  {
    id: 'republiq',
    name: 'RepubliQ Sports Bar',
    category: 'bar',
    photoKw: 'sportsbar,beer',
    lat: 17.7270, lng: 83.3150,
    score: 7.6, price: '₹₹',
    area: 'Waltair Uplands',
    blurb: 'Big screens, bigger pitchers. Where the city watches India play.',
  },
];

export const getSpot = (id) => SPOTS.find((s) => s.id === id);
export const getCategory = (key) => CATEGORIES[key] || CATEGORIES.food;
